/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import java.util.*;
import clases.conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author fabia_000
 */
public class agregarUsuarios extends javax.swing.JFrame {

    String user;

    /**
     * Creates new form agregarUsuarios
     */
    public agregarUsuarios() {
        initComponents();
        user = Interfaz.user;

        setTitle("Registrar nuevo usuario - sesion de " + user);
        setResizable(false);
        setLocationRelativeTo(null);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("iconos/iconopequeño.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jLabel_Nombre2 = new javax.swing.JLabel();
        jLabel_Nombre3 = new javax.swing.JLabel();
        jPassword_add = new javax.swing.JPasswordField();
        jTex_Username = new javax.swing.JTextField();
        jTex_Nombre = new javax.swing.JTextField();
        listaBox = new javax.swing.JComboBox<>();
        jLabel_Nombre4 = new javax.swing.JLabel();
        Btn_add = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel_FAU = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de usuarios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel_Nombre.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Nombre.setText("Username:");
        getContentPane().add(jLabel_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        jLabel_Nombre2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel_Nombre2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Nombre2.setText("Password");
        getContentPane().add(jLabel_Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        jLabel_Nombre3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel_Nombre3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Nombre3.setText("Nivel :");
        getContentPane().add(jLabel_Nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        getContentPane().add(jPassword_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 170, 27));
        getContentPane().add(jTex_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 170, 27));
        getContentPane().add(jTex_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 170, 27));

        listaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Auxiliar" }));
        listaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaBoxActionPerformed(evt);
            }
        });
        getContentPane().add(listaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 170, 27));

        jLabel_Nombre4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel_Nombre4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Nombre4.setText("Nombre :");
        getContentPane().add(jLabel_Nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        Btn_add.setBackground(new java.awt.Color(153, 255, 255));
        Btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add.png"))); // NOI18N
        Btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_addActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 105, 105));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Creado por ribax@gimail.com ®");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        jLabel_FAU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/fondoRegis.jpg"))); // NOI18N
        getContentPane().add(jLabel_FAU, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaBoxActionPerformed

    private void Btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_addActionPerformed

        // tipo Variables para los campos "agregar usuarios"
        int permisos_cmb, validacion = 0;
        String nombre, username, pass, permisos_string = "";

        // definir variables
        nombre = jTex_Nombre.getText().trim();
        username = jTex_Username.getText().trim();
        pass = jPassword_add.getText().trim();
        permisos_cmb = listaBox.getSelectedIndex() + 1;
        other mensAdd = new other();
        boolean val = mensAdd.validacion(nombre,0);

        // validaciones para que no quede ningun campo vacio
        if (val != true) {
            jTex_Nombre.setBackground(Color.orange);
            validacion++;
            JOptionPane.showMessageDialog(null, "El nombre no puede contener numeros");
            return;
        }
        if (nombre.equals("")) {

            jTex_Nombre.setBackground(Color.orange);
            validacion++;

        }
        if (username.equals("")) {

            jTex_Username.setBackground(Color.orange);
            validacion++;

        }
        if (pass.equals("")) {

            jPassword_add.setBackground(Color.orange);
            validacion++;

        }

        // validaciones para asignar los estados        
        if (permisos_cmb == 1) {
            permisos_string = "Administrador";
        } else if (permisos_cmb == 2) {
            permisos_string = "Auxliar";
        }

        //validacion en base de datos de ususarios disponibles
        try {
            Connection cn = conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select username from usuarios where username = '" + username + "'");

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                jTex_Username.setBackground(Color.ORANGE);
                JOptionPane.showMessageDialog(null, "Nombre de usuario no disponible");
                cn.close();
            } else {

                cn.close();

                // Ingresar nuevos usuarios a la base de datos
                if (validacion == 0) {
                    try {
                        Connection cn2 = conexion.conectar();
                        // instrucciones colsultas
                        PreparedStatement pst2 = cn2.prepareStatement(
                                " insert into usuarios values (?,?,?,?,?,?)");

                        pst2.setInt(1, 0);
                        pst2.setString(2, nombre);
                        pst2.setString(3, username);
                        pst2.setString(4, pass);
                        pst2.setString(5, permisos_string);
                        pst2.setString(6, "Activo");

                        pst2.executeUpdate();
                        cn2.close();

                        Limpiar();

                        jTex_Nombre.setBackground(Color.green);
                        jTex_Username.setBackground(Color.green);
                        jPassword_add.setBackground(Color.green);

                        JOptionPane.showMessageDialog(null, "Registro exitoso");
                        this.dispose();

                    } catch (SQLException e) {
                        System.err.println("ERROR al registrar el usuario");
                        JOptionPane.showMessageDialog(null, "¡¡ERROR al registrar!!, contacte al administrador");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
                }

            }
        } catch (SQLException e) {
            System.err.println("Error al validar el nombre de usuario." + e);
            JOptionPane.showMessageDialog(null, "¡¡ ERROR al comparar usuario!!, contacte al administrador.");
        }


    }//GEN-LAST:event_Btn_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_add;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_FAU;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Nombre2;
    private javax.swing.JLabel jLabel_Nombre3;
    private javax.swing.JLabel jLabel_Nombre4;
    private javax.swing.JPasswordField jPassword_add;
    private javax.swing.JTextField jTex_Nombre;
    private javax.swing.JTextField jTex_Username;
    private javax.swing.JComboBox<String> listaBox;
    // End of variables declaration//GEN-END:variables

    public void Limpiar() {
        jTex_Nombre.setText("");
        jTex_Username.setText("");
        jPassword_add.setText("");
        listaBox.setSelectedIndex(0);
    }

}
