/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import clases.conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author fabia_000
 */
public class añadirDos extends javax.swing.JPanel {

    String user;
    String fecha;

    /**
     * Creates new form añadirDos
     */
    public añadirDos() {
        initComponents();
        other mensajero = new other();
        user = Interfaz.user;
        fecha = mensajero.getAnio() + "-" + mensajero.getMes() + "-" + mensajero.getDia();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bton_agregar = new javax.swing.JButton();
        cbxTipo = new javax.swing.JComboBox<>();
        añadirUnidad = new javax.swing.JTextField();
        añadirDes = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bton_agregar.setText("jButton1");
        bton_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bton_agregarActionPerformed(evt);
            }
        });
        add(bton_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 179, -1, -1));

        cbxTipo.setMaximumRowCount(10);
        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pc", "Movil", "Cargador", "Audifonos", "Reloj", "TV", "Conso" }));
        cbxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoActionPerformed(evt);
            }
        });
        add(cbxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));
        add(añadirUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 120, 50));
        add(añadirDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 110, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void bton_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bton_agregarActionPerformed
        int tipo_cmb, validacion = 0;
        String Descripcion, unidades, tipo_string = "";
        other mesajeroDos = new other();

        // definir variables
        Descripcion = añadirDes.getText().trim();
        unidades = añadirUnidad.getText().trim();
        boolean vali = mesajeroDos.validacion(unidades);

        tipo_cmb = cbxTipo.getSelectedIndex() + 1;

        if (Descripcion.equals("")) {

            añadirDes.setBackground(Color.orange);
            validacion++;

        }
        if (unidades.equals("")) {

            añadirUnidad.setBackground(Color.orange);
            validacion++;

        }
        
        
        if (vali != true) {
            añadirUnidad.setBackground(Color.orange);
            validacion++;
            JOptionPane.showMessageDialog(null, "No pudes ingresar Texto");
            return;             
        } 

        //
        if (tipo_cmb == 1) {
            tipo_string = "PC";
        } else if (tipo_cmb == 2) {
            tipo_string = "Movil";
        } else if (tipo_cmb == 3) {
            tipo_string = "Cargador";
        } else if (tipo_cmb == 4) {
            tipo_string = "Audifonos";
        } else if (tipo_cmb == 5) {
            tipo_string = "Reloj";
        } else if (tipo_cmb == 6) {
            tipo_string = "TV";
        } else if (tipo_cmb == 7) {
            tipo_string = "Consola";
        }

        
        
        //
        if (validacion == 0) {
            try {
                Connection cn2 = conexion.conectar();
                PreparedStatement pst2 = cn2.prepareStatement(
                        " insert into inventario values (?,?,?,?,?,?)");

                pst2.setInt(1, 0);
                pst2.setString(2, Descripcion);
                pst2.setString(3, unidades);
                pst2.setString(4, tipo_string);
                pst2.setString(5, fecha);
                pst2.setString(6, user);

                pst2.executeUpdate();
                cn2.close();

                añadirDes.setBackground(Color.green);
                añadirUnidad.setBackground(Color.green);
                JOptionPane.showMessageDialog(null, "Registro exitoso");

            } catch (SQLException e) {
                System.err.println("ERROR al registrar el producto");
                JOptionPane.showMessageDialog(null, "¡¡ERROR al registrar!!, contacte al administrador");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
        }


    }//GEN-LAST:event_bton_agregarActionPerformed

    private void cbxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField añadirDes;
    private javax.swing.JTextField añadirUnidad;
    private javax.swing.JButton bton_agregar;
    private javax.swing.JComboBox<String> cbxTipo;
    // End of variables declaration//GEN-END:variables
}
